language: node_js
node_js:
- 6.9.1
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - fumes.com.br
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/srv/fumes.com.br/
  - REMOTE_USER=deploy
  - REMOTE_HOST=fumes.com.br
before_install:
- openssl aes-256-cbc -K $encrypted_9aaa1c87a687_key -iv $encrypted_9aaa1c87a687_iv
  -in deploy.enc -out deploy -d
- npm install -g npm@^2
install:
- npm install
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
